import 'package:firebase_core/firebase_core.dart';




// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAtBCk8WrsZ04hPsunqRrEzFLxgys1g9U',
    appId: '1:946952783596:android:dd2c0ee060ccb76ae447c9',
    messagingSenderId: '946952783596',
    projectId: 'cusefoodshareapp',
    storageBucket: 'cusefoodshareapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANWH2SAqCvXiOn5VMC9UISe0PgDYZj6Xo',
    appId: '1:946952783596:ios:f87a657469da9551e447c9',
    messagingSenderId: '946952783596',
    projectId: 'cusefoodshareapp',
    storageBucket: 'cusefoodshareapp.firebasestorage.app',
    iosBundleId: 'com.example.cuseFoodShareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANWH2SAqCvXiOn5VMC9UISe0PgDYZj6Xo',
    appId: '1:946952783596:ios:f87a657469da9551e447c9',
    messagingSenderId: '946952783596',
    projectId: 'cusefoodshareapp',
    storageBucket: 'cusefoodshareapp.firebasestorage.app',
    iosBundleId: 'com.example.cuseFoodShareApp',
  );
}

