
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'firebase_options.dart'; // Generated by flutterfire configure
import 'models/app_user.dart';
import 'services/auth_service.dart';
import 'services/firestore_service.dart';
import 'services/storage_service.dart';
import 'services/notification_service.dart';
import 'repositories/auth_repository.dart';
import 'repositories/post_repository.dart';
import 'viewmodels/auth_viewmodel.dart';
import 'viewmodels/home_viewmodel.dart';
import 'views/auth/login_screen.dart';
import 'views/home/home_screen.dart';

void main() async {
  // Ensure Flutter bindings are initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  
  // Initialize Notification Service (run initialization)
  final notificationService = NotificationService();
  await notificationService.initialize();


  // Create instances of services
  final authService = AuthService();
  final firestoreService = FirestoreService();
  final storageService = StorageService();

  // Create instances of repositories, injecting services
  final authRepository = AuthRepository(authService: authService);
  final postRepository = PostRepository(
    firestoreService: firestoreService,
    storageService: storageService,
    authService: authService, // PostRepository needs authService too
  );


  runApp(
    // Use MultiProvider to provide multiple objects down the widget tree
    MultiProvider(
      providers: [
        // Provide Services (if needed directly by UI, usually not in pure MVVM)
        // Provider<AuthService>.value(value: authService),
         Provider<NotificationService>.value(value: notificationService),

        // Provide Repositories (can be useful for creating ViewModels on the fly)
        Provider<AuthRepository>.value(value: authRepository),
        Provider<PostRepository>.value(value: postRepository),

        // Provide ViewModels (ChangeNotifierProvider for state management)
        ChangeNotifierProvider<AuthViewModel>(
          create: (_) => AuthViewModel(authRepository: authRepository),
        ),
         // HomeViewModel can be provided here if it's relatively simple
         // and doesn't need arguments specific to the HomeScreen build context.
         // Otherwise, provide it closer to where it's used (e.g., in AuthWrapper).
         ChangeNotifierProvider<HomeViewModel>(
           create: (_) => HomeViewModel(postRepository: postRepository),
         ),
        // Other ViewModels (like CreatePostViewModel, PostDetailsViewModel)
        // are often created closer to their respective screens using
        // ChangeNotifierProvider or Consumer, especially if they need
        // specific data passed during creation (like a FoodPost object).
      ],
      child: MyApp(),
    ),
  );
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'CuseFoodShare',
      theme: ThemeData(
        primarySwatch: Colors.orange,
        primaryColor: Colors.orange[800], // Darker orange for primary elements
        colorScheme: ColorScheme.fromSwatch(primarySwatch: Colors.orange)
            .copyWith(secondary: Colors.blueAccent), // Accent color
        visualDensity: VisualDensity.adaptivePlatformDensity,
         appBarTheme: AppBarTheme(
            backgroundColor: Colors.orange[800],
            foregroundColor: Colors.white, // Title text color
             elevation: 4.0,
         ),
         elevatedButtonTheme: ElevatedButtonThemeData(
            style: ElevatedButton.styleFrom(
                backgroundColor: Colors.orange[700],
                foregroundColor: Colors.white, // Text color on buttons
                shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(8.0)
                ),
                 padding: EdgeInsets.symmetric(vertical: 12, horizontal: 20),
            )
         ),
         floatingActionButtonTheme: FloatingActionButtonThemeData(
             backgroundColor: Colors.orange[700],
             foregroundColor: Colors.white,
         ),
         cardTheme: CardTheme(
             elevation: 3.0,
             shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(10.0)),
             margin: EdgeInsets.symmetric(vertical: 8.0, horizontal: 5.0),
         ),
         inputDecorationTheme: InputDecorationTheme(
             border: OutlineInputBorder(borderRadius: BorderRadius.circular(8.0)),
             focusedBorder: OutlineInputBorder(
                 borderRadius: BorderRadius.circular(8.0),
                 borderSide: BorderSide(color: Colors.orange[900]!, width: 2.0),
             ),
             labelStyle: TextStyle(color: Colors.grey[700]),
         ),
      ),
      debugShowCheckedModeBanner: false, // Remove debug banner
      home: AuthWrapper(), // Use AuthWrapper to decide which screen to show
    );
  }
}

// Widget to handle authentication state and navigate accordingly
class AuthWrapper extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    // Listen to the authentication status from AuthViewModel
    final authViewModel = Provider.of<AuthViewModel>(context);

    print("AuthWrapper build triggered. Status: ${authViewModel.status}"); // Debug log

    switch (authViewModel.status) {
      case AuthStatus.authenticated:
        print("Navigating to HomeScreen");
        return HomeScreen(); // User is logged in, show Home
      case AuthStatus.unauthenticated:
      case AuthStatus.error: // Show login also on error state
         print("Navigating to LoginScreen");
        return LoginScreen(); // User is not logged in, show Login
      case AuthStatus.authenticating:
      case AuthStatus.uninitialized:
      default:
         print("Showing Loading Screen");
        // Show a loading indicator while checking auth state or authenticating
        return Scaffold(
          body: Center(
            child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                    CircularProgressIndicator(),
                    SizedBox(height: 10),
                    Text("Loading...")
                ],
            ),
          ),
        );
    }
  }
}
